
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DbTest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DbTest
 * 
 */
export type DbTestModel = runtime.Types.Result.DefaultSelection<Prisma.$DbTestPayload>

export type AggregateDbTest = {
  _count: DbTestCountAggregateOutputType | null
  _avg: DbTestAvgAggregateOutputType | null
  _sum: DbTestSumAggregateOutputType | null
  _min: DbTestMinAggregateOutputType | null
  _max: DbTestMaxAggregateOutputType | null
}

export type DbTestAvgAggregateOutputType = {
  id: number | null
}

export type DbTestSumAggregateOutputType = {
  id: number | null
}

export type DbTestMinAggregateOutputType = {
  id: number | null
  status: string | null
  updatedAt: Date | null
}

export type DbTestMaxAggregateOutputType = {
  id: number | null
  status: string | null
  updatedAt: Date | null
}

export type DbTestCountAggregateOutputType = {
  id: number
  status: number
  updatedAt: number
  _all: number
}


export type DbTestAvgAggregateInputType = {
  id?: true
}

export type DbTestSumAggregateInputType = {
  id?: true
}

export type DbTestMinAggregateInputType = {
  id?: true
  status?: true
  updatedAt?: true
}

export type DbTestMaxAggregateInputType = {
  id?: true
  status?: true
  updatedAt?: true
}

export type DbTestCountAggregateInputType = {
  id?: true
  status?: true
  updatedAt?: true
  _all?: true
}

export type DbTestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DbTest to aggregate.
   */
  where?: Prisma.DbTestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbTests to fetch.
   */
  orderBy?: Prisma.DbTestOrderByWithRelationInput | Prisma.DbTestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DbTestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbTests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbTests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DbTests
  **/
  _count?: true | DbTestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DbTestAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DbTestSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DbTestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DbTestMaxAggregateInputType
}

export type GetDbTestAggregateType<T extends DbTestAggregateArgs> = {
      [P in keyof T & keyof AggregateDbTest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDbTest[P]>
    : Prisma.GetScalarType<T[P], AggregateDbTest[P]>
}




export type DbTestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DbTestWhereInput
  orderBy?: Prisma.DbTestOrderByWithAggregationInput | Prisma.DbTestOrderByWithAggregationInput[]
  by: Prisma.DbTestScalarFieldEnum[] | Prisma.DbTestScalarFieldEnum
  having?: Prisma.DbTestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DbTestCountAggregateInputType | true
  _avg?: DbTestAvgAggregateInputType
  _sum?: DbTestSumAggregateInputType
  _min?: DbTestMinAggregateInputType
  _max?: DbTestMaxAggregateInputType
}

export type DbTestGroupByOutputType = {
  id: number
  status: string
  updatedAt: Date
  _count: DbTestCountAggregateOutputType | null
  _avg: DbTestAvgAggregateOutputType | null
  _sum: DbTestSumAggregateOutputType | null
  _min: DbTestMinAggregateOutputType | null
  _max: DbTestMaxAggregateOutputType | null
}

export type GetDbTestGroupByPayload<T extends DbTestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DbTestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DbTestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DbTestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DbTestGroupByOutputType[P]>
      }
    >
  >



export type DbTestWhereInput = {
  AND?: Prisma.DbTestWhereInput | Prisma.DbTestWhereInput[]
  OR?: Prisma.DbTestWhereInput[]
  NOT?: Prisma.DbTestWhereInput | Prisma.DbTestWhereInput[]
  id?: Prisma.IntFilter<"DbTest"> | number
  status?: Prisma.StringFilter<"DbTest"> | string
  updatedAt?: Prisma.DateTimeFilter<"DbTest"> | Date | string
}

export type DbTestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DbTestWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.DbTestWhereInput | Prisma.DbTestWhereInput[]
  OR?: Prisma.DbTestWhereInput[]
  NOT?: Prisma.DbTestWhereInput | Prisma.DbTestWhereInput[]
  status?: Prisma.StringFilter<"DbTest"> | string
  updatedAt?: Prisma.DateTimeFilter<"DbTest"> | Date | string
}, "id">

export type DbTestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DbTestCountOrderByAggregateInput
  _avg?: Prisma.DbTestAvgOrderByAggregateInput
  _max?: Prisma.DbTestMaxOrderByAggregateInput
  _min?: Prisma.DbTestMinOrderByAggregateInput
  _sum?: Prisma.DbTestSumOrderByAggregateInput
}

export type DbTestScalarWhereWithAggregatesInput = {
  AND?: Prisma.DbTestScalarWhereWithAggregatesInput | Prisma.DbTestScalarWhereWithAggregatesInput[]
  OR?: Prisma.DbTestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DbTestScalarWhereWithAggregatesInput | Prisma.DbTestScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"DbTest"> | number
  status?: Prisma.StringWithAggregatesFilter<"DbTest"> | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DbTest"> | Date | string
}

export type DbTestCreateInput = {
  id?: number
  status?: string
  updatedAt?: Date | string
}

export type DbTestUncheckedCreateInput = {
  id?: number
  status?: string
  updatedAt?: Date | string
}

export type DbTestUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbTestUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbTestCreateManyInput = {
  id?: number
  status?: string
  updatedAt?: Date | string
}

export type DbTestUpdateManyMutationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbTestUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DbTestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DbTestAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type DbTestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DbTestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DbTestSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type DbTestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  status?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["dbTest"]>

export type DbTestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  status?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["dbTest"]>

export type DbTestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  status?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["dbTest"]>

export type DbTestSelectScalar = {
  id?: boolean
  status?: boolean
  updatedAt?: boolean
}

export type DbTestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "status" | "updatedAt", ExtArgs["result"]["dbTest"]>

export type $DbTestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DbTest"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    status: string
    updatedAt: Date
  }, ExtArgs["result"]["dbTest"]>
  composites: {}
}

export type DbTestGetPayload<S extends boolean | null | undefined | DbTestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DbTestPayload, S>

export type DbTestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DbTestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DbTestCountAggregateInputType | true
  }

export interface DbTestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DbTest'], meta: { name: 'DbTest' } }
  /**
   * Find zero or one DbTest that matches the filter.
   * @param {DbTestFindUniqueArgs} args - Arguments to find a DbTest
   * @example
   * // Get one DbTest
   * const dbTest = await prisma.dbTest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DbTestFindUniqueArgs>(args: Prisma.SelectSubset<T, DbTestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DbTestClient<runtime.Types.Result.GetResult<Prisma.$DbTestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DbTest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DbTestFindUniqueOrThrowArgs} args - Arguments to find a DbTest
   * @example
   * // Get one DbTest
   * const dbTest = await prisma.dbTest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DbTestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DbTestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DbTestClient<runtime.Types.Result.GetResult<Prisma.$DbTestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DbTest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbTestFindFirstArgs} args - Arguments to find a DbTest
   * @example
   * // Get one DbTest
   * const dbTest = await prisma.dbTest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DbTestFindFirstArgs>(args?: Prisma.SelectSubset<T, DbTestFindFirstArgs<ExtArgs>>): Prisma.Prisma__DbTestClient<runtime.Types.Result.GetResult<Prisma.$DbTestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DbTest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbTestFindFirstOrThrowArgs} args - Arguments to find a DbTest
   * @example
   * // Get one DbTest
   * const dbTest = await prisma.dbTest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DbTestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DbTestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DbTestClient<runtime.Types.Result.GetResult<Prisma.$DbTestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DbTests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbTestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DbTests
   * const dbTests = await prisma.dbTest.findMany()
   * 
   * // Get first 10 DbTests
   * const dbTests = await prisma.dbTest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dbTestWithIdOnly = await prisma.dbTest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DbTestFindManyArgs>(args?: Prisma.SelectSubset<T, DbTestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbTestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DbTest.
   * @param {DbTestCreateArgs} args - Arguments to create a DbTest.
   * @example
   * // Create one DbTest
   * const DbTest = await prisma.dbTest.create({
   *   data: {
   *     // ... data to create a DbTest
   *   }
   * })
   * 
   */
  create<T extends DbTestCreateArgs>(args: Prisma.SelectSubset<T, DbTestCreateArgs<ExtArgs>>): Prisma.Prisma__DbTestClient<runtime.Types.Result.GetResult<Prisma.$DbTestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DbTests.
   * @param {DbTestCreateManyArgs} args - Arguments to create many DbTests.
   * @example
   * // Create many DbTests
   * const dbTest = await prisma.dbTest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DbTestCreateManyArgs>(args?: Prisma.SelectSubset<T, DbTestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DbTests and returns the data saved in the database.
   * @param {DbTestCreateManyAndReturnArgs} args - Arguments to create many DbTests.
   * @example
   * // Create many DbTests
   * const dbTest = await prisma.dbTest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DbTests and only return the `id`
   * const dbTestWithIdOnly = await prisma.dbTest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DbTestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DbTestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbTestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DbTest.
   * @param {DbTestDeleteArgs} args - Arguments to delete one DbTest.
   * @example
   * // Delete one DbTest
   * const DbTest = await prisma.dbTest.delete({
   *   where: {
   *     // ... filter to delete one DbTest
   *   }
   * })
   * 
   */
  delete<T extends DbTestDeleteArgs>(args: Prisma.SelectSubset<T, DbTestDeleteArgs<ExtArgs>>): Prisma.Prisma__DbTestClient<runtime.Types.Result.GetResult<Prisma.$DbTestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DbTest.
   * @param {DbTestUpdateArgs} args - Arguments to update one DbTest.
   * @example
   * // Update one DbTest
   * const dbTest = await prisma.dbTest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DbTestUpdateArgs>(args: Prisma.SelectSubset<T, DbTestUpdateArgs<ExtArgs>>): Prisma.Prisma__DbTestClient<runtime.Types.Result.GetResult<Prisma.$DbTestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DbTests.
   * @param {DbTestDeleteManyArgs} args - Arguments to filter DbTests to delete.
   * @example
   * // Delete a few DbTests
   * const { count } = await prisma.dbTest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DbTestDeleteManyArgs>(args?: Prisma.SelectSubset<T, DbTestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DbTests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbTestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DbTests
   * const dbTest = await prisma.dbTest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DbTestUpdateManyArgs>(args: Prisma.SelectSubset<T, DbTestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DbTests and returns the data updated in the database.
   * @param {DbTestUpdateManyAndReturnArgs} args - Arguments to update many DbTests.
   * @example
   * // Update many DbTests
   * const dbTest = await prisma.dbTest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DbTests and only return the `id`
   * const dbTestWithIdOnly = await prisma.dbTest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DbTestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DbTestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DbTestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DbTest.
   * @param {DbTestUpsertArgs} args - Arguments to update or create a DbTest.
   * @example
   * // Update or create a DbTest
   * const dbTest = await prisma.dbTest.upsert({
   *   create: {
   *     // ... data to create a DbTest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DbTest we want to update
   *   }
   * })
   */
  upsert<T extends DbTestUpsertArgs>(args: Prisma.SelectSubset<T, DbTestUpsertArgs<ExtArgs>>): Prisma.Prisma__DbTestClient<runtime.Types.Result.GetResult<Prisma.$DbTestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DbTests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbTestCountArgs} args - Arguments to filter DbTests to count.
   * @example
   * // Count the number of DbTests
   * const count = await prisma.dbTest.count({
   *   where: {
   *     // ... the filter for the DbTests we want to count
   *   }
   * })
  **/
  count<T extends DbTestCountArgs>(
    args?: Prisma.Subset<T, DbTestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DbTestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DbTest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbTestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DbTestAggregateArgs>(args: Prisma.Subset<T, DbTestAggregateArgs>): Prisma.PrismaPromise<GetDbTestAggregateType<T>>

  /**
   * Group by DbTest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DbTestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DbTestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DbTestGroupByArgs['orderBy'] }
      : { orderBy?: DbTestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DbTestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDbTestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DbTest model
 */
readonly fields: DbTestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DbTest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DbTestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DbTest model
 */
export interface DbTestFieldRefs {
  readonly id: Prisma.FieldRef<"DbTest", 'Int'>
  readonly status: Prisma.FieldRef<"DbTest", 'String'>
  readonly updatedAt: Prisma.FieldRef<"DbTest", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DbTest findUnique
 */
export type DbTestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbTest
   */
  select?: Prisma.DbTestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbTest
   */
  omit?: Prisma.DbTestOmit<ExtArgs> | null
  /**
   * Filter, which DbTest to fetch.
   */
  where: Prisma.DbTestWhereUniqueInput
}

/**
 * DbTest findUniqueOrThrow
 */
export type DbTestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbTest
   */
  select?: Prisma.DbTestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbTest
   */
  omit?: Prisma.DbTestOmit<ExtArgs> | null
  /**
   * Filter, which DbTest to fetch.
   */
  where: Prisma.DbTestWhereUniqueInput
}

/**
 * DbTest findFirst
 */
export type DbTestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbTest
   */
  select?: Prisma.DbTestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbTest
   */
  omit?: Prisma.DbTestOmit<ExtArgs> | null
  /**
   * Filter, which DbTest to fetch.
   */
  where?: Prisma.DbTestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbTests to fetch.
   */
  orderBy?: Prisma.DbTestOrderByWithRelationInput | Prisma.DbTestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DbTests.
   */
  cursor?: Prisma.DbTestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbTests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbTests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbTests.
   */
  distinct?: Prisma.DbTestScalarFieldEnum | Prisma.DbTestScalarFieldEnum[]
}

/**
 * DbTest findFirstOrThrow
 */
export type DbTestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbTest
   */
  select?: Prisma.DbTestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbTest
   */
  omit?: Prisma.DbTestOmit<ExtArgs> | null
  /**
   * Filter, which DbTest to fetch.
   */
  where?: Prisma.DbTestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbTests to fetch.
   */
  orderBy?: Prisma.DbTestOrderByWithRelationInput | Prisma.DbTestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DbTests.
   */
  cursor?: Prisma.DbTestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbTests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbTests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbTests.
   */
  distinct?: Prisma.DbTestScalarFieldEnum | Prisma.DbTestScalarFieldEnum[]
}

/**
 * DbTest findMany
 */
export type DbTestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbTest
   */
  select?: Prisma.DbTestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbTest
   */
  omit?: Prisma.DbTestOmit<ExtArgs> | null
  /**
   * Filter, which DbTests to fetch.
   */
  where?: Prisma.DbTestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DbTests to fetch.
   */
  orderBy?: Prisma.DbTestOrderByWithRelationInput | Prisma.DbTestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DbTests.
   */
  cursor?: Prisma.DbTestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DbTests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DbTests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DbTests.
   */
  distinct?: Prisma.DbTestScalarFieldEnum | Prisma.DbTestScalarFieldEnum[]
}

/**
 * DbTest create
 */
export type DbTestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbTest
   */
  select?: Prisma.DbTestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbTest
   */
  omit?: Prisma.DbTestOmit<ExtArgs> | null
  /**
   * The data needed to create a DbTest.
   */
  data: Prisma.XOR<Prisma.DbTestCreateInput, Prisma.DbTestUncheckedCreateInput>
}

/**
 * DbTest createMany
 */
export type DbTestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DbTests.
   */
  data: Prisma.DbTestCreateManyInput | Prisma.DbTestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DbTest createManyAndReturn
 */
export type DbTestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbTest
   */
  select?: Prisma.DbTestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DbTest
   */
  omit?: Prisma.DbTestOmit<ExtArgs> | null
  /**
   * The data used to create many DbTests.
   */
  data: Prisma.DbTestCreateManyInput | Prisma.DbTestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DbTest update
 */
export type DbTestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbTest
   */
  select?: Prisma.DbTestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbTest
   */
  omit?: Prisma.DbTestOmit<ExtArgs> | null
  /**
   * The data needed to update a DbTest.
   */
  data: Prisma.XOR<Prisma.DbTestUpdateInput, Prisma.DbTestUncheckedUpdateInput>
  /**
   * Choose, which DbTest to update.
   */
  where: Prisma.DbTestWhereUniqueInput
}

/**
 * DbTest updateMany
 */
export type DbTestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DbTests.
   */
  data: Prisma.XOR<Prisma.DbTestUpdateManyMutationInput, Prisma.DbTestUncheckedUpdateManyInput>
  /**
   * Filter which DbTests to update
   */
  where?: Prisma.DbTestWhereInput
  /**
   * Limit how many DbTests to update.
   */
  limit?: number
}

/**
 * DbTest updateManyAndReturn
 */
export type DbTestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbTest
   */
  select?: Prisma.DbTestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DbTest
   */
  omit?: Prisma.DbTestOmit<ExtArgs> | null
  /**
   * The data used to update DbTests.
   */
  data: Prisma.XOR<Prisma.DbTestUpdateManyMutationInput, Prisma.DbTestUncheckedUpdateManyInput>
  /**
   * Filter which DbTests to update
   */
  where?: Prisma.DbTestWhereInput
  /**
   * Limit how many DbTests to update.
   */
  limit?: number
}

/**
 * DbTest upsert
 */
export type DbTestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbTest
   */
  select?: Prisma.DbTestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbTest
   */
  omit?: Prisma.DbTestOmit<ExtArgs> | null
  /**
   * The filter to search for the DbTest to update in case it exists.
   */
  where: Prisma.DbTestWhereUniqueInput
  /**
   * In case the DbTest found by the `where` argument doesn't exist, create a new DbTest with this data.
   */
  create: Prisma.XOR<Prisma.DbTestCreateInput, Prisma.DbTestUncheckedCreateInput>
  /**
   * In case the DbTest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DbTestUpdateInput, Prisma.DbTestUncheckedUpdateInput>
}

/**
 * DbTest delete
 */
export type DbTestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbTest
   */
  select?: Prisma.DbTestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbTest
   */
  omit?: Prisma.DbTestOmit<ExtArgs> | null
  /**
   * Filter which DbTest to delete.
   */
  where: Prisma.DbTestWhereUniqueInput
}

/**
 * DbTest deleteMany
 */
export type DbTestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DbTests to delete
   */
  where?: Prisma.DbTestWhereInput
  /**
   * Limit how many DbTests to delete.
   */
  limit?: number
}

/**
 * DbTest without action
 */
export type DbTestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DbTest
   */
  select?: Prisma.DbTestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DbTest
   */
  omit?: Prisma.DbTestOmit<ExtArgs> | null
}
